services:
  backend:
    build:
      context: ./conduit-backend
    image: conduit-backend:v1
    container_name: backend
    ports:
      - "2222:8383"
    restart: unless-stopped
    env_file:
      - ./conduit-backend/.env
    volumes:
      - local_data_back:/app/media

  frontend:
    build:
      context: ./conduit-frontend
    image: conduit-frontend:v1
    container_name: frontend
    ports:
      - "8282:80"
    restart: unless-stoppedg
    env_file:
      - ./conduit-frontend/.env
    depends_on:
      - backend

volumes:
  local_data_back:
