services:
  backend:
    build:
      context: ./backend/conduit-backend
    image: conduit-backend:v1
    container_name: backend
    ports:
      - "2222:8383"
    restart: unless-stopped
    env_file:
      - ./backend/conduit-backend/.env
    volumes:
      - local_data_back:/app/media

  frontend:
    build:
      context: ./frontend/conduit-frontend
    image: conduit-frontend:v1
    container_name: frontend
    ports:
      - "1111:8282"
    restart: unless-stopped
    env_file:
      - ./frontend/conduit-frontend/.env
    depends_on:
      - backend

volumes:
  local_data_back:
